<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AuthKit.Core\AuthKit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Scalar.AspNetCore" Version="2.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
